// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 13,
  states: "nQYQPOOOOQO'#Ce'#CeOOQO'#Ca'#CaQYQPOOOOQO-E6_-E6_",
  stateData: "b~OWOSPOS~ORPOSPO~O",
  goto: "eYPPPPPZPPPaQRORSRTQOR",
  nodeNames: "⚠ LineComment Tex Commands Args",
  maxTerm: 9,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "$a~RVXYhYZh]^hpqhuvy!}#O!U#O#P#o~mSW~XYhYZh]^hpqh~!OQP~OYyZ~y~!XX|}!t}!O!t!O!P!t!Q![!t![!]!t!_!`!t!c!}!t#O#P!t#T#o!t~!wZYZ#j|}!t}!O!t!O!P!t!Q![!t![!]!t!_!`!t!c!}!t#O#P!t#P#Q#j#T#o!t~#oOS~~#rS|}$O!Q![$O!c!}$O#T#o$O~$TSR~|}$O!Q![$O!c!}$O#T#o$O",
  tokenizers: [0],
  topRules: {"Tex":[0,2]},
  tokenPrec: 0
})
